---
title: "tag_dx"
author: "cfm"
date: "9/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
```

```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}
## Load required packages ##
packages <-  c("tidyverse", 
               "nlme", "ggplot2")
lapply(packages, library, character.only = TRUE)
```

Set root path for Clare (laptop)
```{r}
root_path="/Users/clare/Desktop/projects/tag_dx/working_docs/"
```

Set root path for work computer 
```{r}
root_path="~/Desktop/Projects/dx/working_docs/"
```

```{r Load data sets}
##pulling CSV files & calculating cronbach alpha
dx_full<-read.csv(paste0(root_path,"Lifetime_Diagnoses.csv"),
                  stringsAsFactors = FALSE) 
#dx_names<-read.csv(paste0(root_path,"dx_names.csv"),
                  #stringsAsFactors = FALSE)
```

```{r new diagnoses??}

## creating  dx type variable (anxiety vs mood vs eating disorder)

## creating doc to get each individual acronym used 

dx_names <- unique(dx_names)

## exporting doc to see if there are any new mutations to add below 

write_csv(dx_names, "dx_names.csv")

```

```{r cleaning}
## (anxiety = 1, mood = 2, disordered eating = 3) as of 09/08/2021

dx_full$dx_type <- dx_full$dx

dx_full <- dx_full %>%
  mutate(dx_type=ifelse(dx_type=="MDD", 2,
                          ifelse(dx_type=="SocP", 1,
                                 ifelse(dx_type=="ADDM", 2,
                                        ifelse(dx_type=="SimP", 1,
                                               ifelse(dx_type=="ENU", 1,
                                                      ifelse(dx_type=="GAD", 1,
                                                             ifelse(dx_type=="OCD", 1,
                                                                    ifelse(dx_type=="DNOS", 2,
                                                                           ifelse(dx_type=="PTSD", 1,
                                                                                  ifelse(dx_type=="AG", 1,
                                                                                         ifelse(dx_type=="PD", 1,
                                                                                                ifelse(dx_type=="AN", 3,
                                                                                                       ifelse(dx_type=="EDNOS", 3,
                                                                                                                     ifelse(dx_type=="BU", 3,
                                                                                                                            ifelse(dx_type=="ANOS", 1, 
                                                                                                                                          ifelse(dx_type=="BP2", 2,
                                                                                                                                                        ifelse(dx_type=="BP1", 2,
                                                                                                                                                                      ifelse(dx_type=="ADA", 1,
                                                                                                                                                                             ifelse(dx_type=="ASD", 1,                                                                                      ifelse(dx_type=="Schizo_Affect_Dep", 2,
                                                                                                                                                                                                  ifelse(dx_type=="DYS", 2,
                                                                                                                                                                                                         ifelse(dx_type=="ManEp", 2,
                                                                                                                                                                                                                ifelse(dx_type=="HypoEp", 2,
                                                                                                                                                                                                                       ifelse(dx_type=="PD_AG", 1,
                                                                                                                                                                                                                                     ifelse(dx_type=="SepAnx", 1,
                                                                                                                                                                                                                                            ifelse(dx_type=="MDD_B", 2,
                                                                                                                                                                                                                                                          ifelse(dx_type=="MixedEp_Psychotic", 2,                                                                                        dx_type))))))))))))))))))))))))))))

## creating wave docs 

## W1 

w1_dx_current <-  dx_full[which(dx_full$W1_current=="1"),]
w1_dx_past <- dx_full[which(dx_full$W1_past=="1"),]
w1_dx <- full_join(w1_dx_current, w1_dx_past)

## W2

w2_dx_current <-  dx_full[which(dx_full$W2_current=="1"),]
w2_dx_past <- dx_full[which(dx_full$W2_past=="1"),]
w2_dx <- full_join(w2_dx_current, w2_dx_past)
                                                                    
## W3

w3_dx_current <-  dx_full[which(dx_full$W3_current=="1"),]
w3_dx_past <- dx_full[which(dx_full$W3_past=="1"),]
w3_dx <- full_join(w3_dx_current, w3_dx_past)
         
```

```{r Questions}

## How many participants met for any anxiety/mood/ed disorder in each wave?

## W1 

w1_dx_anxiety <-  w1_dx[which(w1_dx$dx_type=="1"),]
w1_dx_mood <- w1_dx[which(w1_dx$dx_type=="2"),]
w1_dx_ed <- w1_dx[which(w1_dx$dx_type=="3"),]

w1_dx_anxiety <- w1_dx_anxiety[!duplicated(w1_dx_anxiety$ID), ] ## 35 PARTICIPANTS 
w1_dx_mood <- w1_dx_mood[!duplicated(w1_dx_mood$ID), ] ## 12 PARTICIPANTS 
w1_dx_ed <- w1_dx_ed[!duplicated(w1_dx_ed$ID), ] ## 0 PARTICIPANTS 

## W2 

w2_dx_anxiety <-  w2_dx[which(w2_dx$dx_type=="1"),]
w2_dx_mood <- w2_dx[which(w2_dx$dx_type=="2"),]
w2_dx_ed <- w2_dx[which(w2_dx$dx_type=="3"),]

w2_dx_anxiety <- w2_dx_anxiety[!duplicated(w2_dx_anxiety$ID), ]  ## 43 PARTICIPANTS
w2_dx_mood <- w2_dx_mood[!duplicated(w2_dx_mood$ID), ]  ## 31 PARTICIPANTS 
w2_dx_ed <- w2_dx_ed[!duplicated(w2_dx_ed$ID), ] ## 2 PARTICIPANTS 

## W3 

w3_dx_anxiety <-  w3_dx[which(w3_dx$dx_type=="1"),]
w3_dx_mood <- w3_dx[which(w3_dx$dx_type=="2"),]
w3_dx_ed <- w3_dx[which(w3_dx$dx_type=="3"),]

w3_dx_anxiety <- w3_dx_anxiety[!duplicated(w3_dx_anxiety$ID), ]  ## 42 PARTICIPANTS
w3_dx_mood <- w3_dx_mood[!duplicated(w3_dx_mood$ID), ]  ## 39 PARTICIPANTS 
w3_dx_ed <- w3_dx_ed[!duplicated(w3_dx_ed$ID), ] ## 10 PARTICIPANTS

## How many participants are currently experiencing anxiety/mood/disordered eating? 

## W1 

w1_dx_anxiety_current <-  w1_dx_current[which(w1_dx_current$dx_type=="1"),]
w1_dx_mood_current <- w1_dx_current[which(w1_dx_current$dx_type=="2"),]
w1_dx_ed_current <- w1_dx_current[which(w1_dx_current$dx_type=="3"),]

w1_dx_anxiety_current <- w1_dx_anxiety_current[!duplicated(w1_dx_anxiety_current$ID), ] ## 24 PARTICIPANTS
w1_dx_mood_current <- w1_dx_mood_current[!duplicated(w1_dx_mood_current$ID), ] ## 5 PARTICIPANTS 
w1_dx_ed_current <- w1_dx_ed_current[!duplicated(w1_dx_ed_current$ID), ] ## 0 PARTICIPANTS

## W2

w2_dx_anxiety_current <-  w2_dx_current[which(w2_dx_current$dx_type=="1"),]
w2_dx_mood_current <- w2_dx_current[which(w2_dx_current$dx_type=="2"),]
w2_dx_ed_current <- w2_dx_current[which(w2_dx_current$dx_type=="3"),]

w2_dx_anxiety_current <- w2_dx_anxiety_current[!duplicated(w2_dx_anxiety_current$ID), ] ## 38 PARTICIPANTS
w2_dx_mood_current <- w2_dx_mood_current[!duplicated(w2_dx_mood_current$ID), ] ## 15 PARTICIPANTS 
w2_dx_ed_current <- w2_dx_ed_current[!duplicated(w2_dx_ed_current$ID), ] ## 0 PARTICIPANTS

## W3

w3_dx_anxiety_current <-  w3_dx_current[which(w3_dx_current$dx_type=="1"),]
w3_dx_mood_current <- w3_dx_current[which(w3_dx_current$dx_type=="2"),]
w3_dx_ed_current <- w3_dx_current[which(w3_dx_current$dx_type=="3"),]

w3_dx_anxiety_current <- w3_dx_anxiety_current[!duplicated(w3_dx_anxiety_current$ID), ] ## 37 PARTICIPANTS
w3_dx_mood_current <- w3_dx_mood_current[!duplicated(w3_dx_mood_current$ID), ] ## 18 PARTICIPANTS 
w3_dx_ed_current <- w3_dx_ed_current[!duplicated(w3_dx_ed_current$ID), ] ## 4 PARTICIPANTS


## How many participants in each wave met for anxiety + mood or anxiety + ed or mood + ed currently?

## W1 

w1_comorbid_current_ma <- w1_dx_mood_current[w1_dx_mood_current$ID %in% w1_dx_anxiety_current$ID,] ## 3
w1_comorbid_current_ae <- w1_dx_anxiety_current[w1_dx_anxiety_current$ID %in% w1_dx_ed_current$ID,] ## 0 
w1_comorbid_current_me <- w1_dx_mood_current[w1_dx_mood_current$ID %in% w1_dx_ed_current$ID,] ## 0
w1_comorbid_current <- full_join(w1_comorbid_current_ae, w1_comorbid_current_ma)
w1_comorbid_current <- full_join(w1_comorbid_current, w1_comorbid_current_me) ## 3 TOTAL

# W2 

w2_comorbid_current_ma <- w2_dx_mood_current[w2_dx_mood_current$ID %in% w2_dx_anxiety_current$ID,] ## 7
w2_comorbid_current_ae <- w2_dx_anxiety_current[w2_dx_anxiety_current$ID %in% w2_dx_ed_current$ID,] ## 0 
w2_comorbid_current_me <- w2_dx_mood_current[w2_dx_mood_current$ID %in% w2_dx_ed_current$ID,] ## 0 
w2_comorbid_current <- full_join(w2_comorbid_current_ae, w2_comorbid_current_ma)
w2_comorbid_current <- full_join(w2_comorbid_current, w2_comorbid_current_me) ## 7 TOTAL

## W3 

w3_comorbid_current_ma <- w3_dx_mood_current[w3_dx_mood_current$ID %in% w3_dx_anxiety_current$ID,] 
w3_comorbid_current_ae <- w3_dx_anxiety_current[w3_dx_anxiety_current$ID %in% w3_dx_ed_current$ID,] 
w3_comorbid_current_me <- w3_dx_mood_current[w3_dx_mood_current$ID %in% w3_dx_ed_current$ID,] 
w3_comorbid_current <- full_join(w3_comorbid_current_ae, w3_comorbid_current_ma)
w3_comorbid_current <- full_join(w3_comorbid_current, w3_comorbid_current_me) ## 18 TOTAL

## How many participants have experienced anxiety/mood/disordered eating in the past two years? 

## W1 

w1_dx_anxiety_past <-  w1_dx_past[which(w1_dx_past$dx_type=="1"),]
w1_dx_mood_past <- w1_dx_past[which(w1_dx_past$dx_type=="2"),]
w1_dx_ed_past <- w1_dx_past[which(w1_dx_past$dx_type=="3"),]

w1_dx_anxiety_past <- w1_dx_anxiety_past[!duplicated(w1_dx_anxiety_past$ID), ] ## 24 PARTICIPANTS
w1_dx_mood_past <- w1_dx_mood_past[!duplicated(w1_dx_mood_past$ID), ] ## 5 PARTICIPANTS 
w1_dx_ed_past <- w1_dx_ed_past[!duplicated(w1_dx_ed_past$ID), ] ## 0 PARTICIPANTS

## W2

w2_dx_anxiety_past <-  w2_dx_past[which(w2_dx_past$dx_type=="1"),]
w2_dx_mood_past <- w2_dx_past[which(w2_dx_past$dx_type=="2"),]
w2_dx_ed_past <- w2_dx_past[which(w2_dx_past$dx_type=="3"),]

w2_dx_anxiety_past <- w2_dx_anxiety_past[!duplicated(w2_dx_anxiety_past$ID), ] ## 38 PARTICIPANTS
w2_dx_mood_past <- w2_dx_mood_past[!duplicated(w2_dx_mood_past$ID), ] ## 15 PARTICIPANTS 
w2_dx_ed_past <- w2_dx_ed_past[!duplicated(w2_dx_ed_past$ID), ] ## 0 PARTICIPANTS

## W3

w3_dx_anxiety_past <-  w3_dx_past[which(w3_dx_past$dx_type=="1"),]
w3_dx_mood_past <- w3_dx_past[which(w3_dx_past$dx_type=="2"),]
w3_dx_ed_past <- w3_dx_past[which(w3_dx_past$dx_type=="3"),]

w3_dx_anxiety_past <- w3_dx_anxiety_past[!duplicated(w3_dx_anxiety_past$ID), ] ## 37 PARTICIPANTS
w3_dx_mood_past <- w3_dx_mood_past[!duplicated(w3_dx_mood_past$ID), ] ## 18 PARTICIPANTS 
w3_dx_ed_past <- w3_dx_ed_past[!duplicated(w3_dx_ed_past$ID), ] ## 4 PARTICIPANTS


## How many participants in each wave met for anxiety + mood or anxiety + ed or mood + ed past?

## W1 

w1_comorbid_past_ma <- w1_dx_mood_past[w1_dx_mood_past$ID %in% w1_dx_anxiety_past$ID,] ## 1
w1_comorbid_past_ae <- w1_dx_anxiety_past[w1_dx_anxiety_past$ID %in% w1_dx_ed_past$ID,] ## 0 
w1_comorbid_past_me <- w1_dx_mood_past[w1_dx_mood_past$ID %in% w1_dx_ed_past$ID,] ## 0
w1_comorbid_past <- full_join(w1_comorbid_past_ae, w1_comorbid_past_ma)
w1_comorbid_past <- full_join(w1_comorbid_past, w1_comorbid_past_me) ## 1 TOTAL

# W2 

w2_comorbid_past_ma <- w2_dx_mood_past[w2_dx_mood_past$ID %in% w2_dx_anxiety_past$ID,] ## 7
w2_comorbid_past_ae <- w2_dx_anxiety_past[w2_dx_anxiety_past$ID %in% w2_dx_ed_past$ID,] ## 0 
w2_comorbid_past_me <- w2_dx_mood_past[w2_dx_mood_past$ID %in% w2_dx_ed_past$ID,] ## 2 
w2_comorbid_past <- full_join(w2_comorbid_past_ae, w2_comorbid_past_ma)
w2_comorbid_past <- full_join(w2_comorbid_past, w2_comorbid_past_me) ## 9 TOTAL

## W3 

w3_comorbid_past_ma <- w3_dx_mood_past[w3_dx_mood_past$ID %in% w3_dx_anxiety_past$ID,] ## 4
w3_comorbid_past_ae <- w3_dx_anxiety_past[w3_dx_anxiety_past$ID %in% w3_dx_ed_past$ID,] ## 2
w3_comorbid_past_me <- w3_dx_mood_past[w3_dx_mood_past$ID %in% w3_dx_ed_past$ID,] ## 4
w3_comorbid_past <- full_join(w3_comorbid_past_ae, w3_comorbid_past_ma)
w3_comorbid_past <- full_join(w3_comorbid_past, w3_comorbid_past_me) ## 8 TOTAL


```

```{r visualizing for all dx}

## visualizing by diagnoses participant

## creating wave variable 


dx_full$Wave_1_C <- paste(dx_full$W1_current)
dx_full$Wave_1_P <- paste(dx_full$W1_past)
dx_full$Wave_2_C <- paste(dx_full$W2_current)
dx_full$Wave_2_P <- paste(dx_full$W2_past)
dx_full$Wave_3_C <- paste(dx_full$W3_current)
dx_full$Wave_3_P <- paste(dx_full$W3_past)

dx_full$Wave_1_C[dx_full$Wave_1_C=="1"] = "1"
dx_full$Wave_1_P[dx_full$Wave_1_P=="1"] = "1"
dx_full$Wave_2_C[dx_full$Wave_2_C=="1"] = "2"
dx_full$Wave_2_P[dx_full$Wave_2_P=="1"] = "2"
dx_full$Wave_3_C[dx_full$Wave_3_C=="1"] = "3"
dx_full$Wave_3_P[dx_full$Wave_3_P=="1"] = "3"

dx_full <- dx_full %>%
  unite("Wave", Wave_1_C:Wave_1_P:Wave_2_C:Wave_2_P:Wave_3_C:Wave_3_P)

dx_full <- dx_full %>%
  mutate(Wave=ifelse(Wave=="1_NA_NA_NA_NA_NA", "1",
                     ifelse(Wave=="NA_1_NA_NA_NA_NA", "1",
                            ifelse(Wave=="NA_NA_2_NA_NA_NA", "2",
                                   ifelse(Wave=="NA_NA_NA_2_NA_NA", "2",
                                          ifelse(Wave=="NA_NA_NA_NA_3_NA", "3",
                                                 ifelse(Wave=="NA_NA_NA_NA_NA_3", "3",
                                                        Wave)))))))

dx_full$Wave <- as.factor(dx_full$Wave)
dx_full$dx_type <- as.integer(dx_full$dx_type)

dx_full$onset_age_months_decimal <- dx_full$onset_age_months/12

dx_full$onset_age <- dx_full$onset_age_years + dx_full$onset_age_months_decimal

dx_full <-  dx_full[-c(1,2),]

dx_by_px<- ggplot(dx_full,
                           aes(x=dx_type,
                               y=onset_age,
                               group=ID,
                               col=Wave,
                               shape=Wave)) + 
  geom_point(alpha=1) + 
  geom_line(alpha=.4)+
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("W1", "W2", "W3"),
                     values = c("#5445b1", "#749dae", "#f3c483"))  +
  scale_shape_manual(name= "Wave",
              labels= c("W1", "W2", "W3"),
              values = c(0, 1, 2))+
  ylab("Age of Onset (years)") +
	ylim(5, 16) +
  xlab("Diagnosis Type")+
  scale_x_continuous(breaks = 1:3,
  labels = paste0(c("Anxiety", "Mood", "Eating")))+
  theme_minimal()


```

```{r visualizing just depressive disorders}

## creating document with just depressive disorders 

dx_depressive_MDD <-  dx_full[which(dx_full$dx=="MDD"),]
dx_depressive_DYS <-  dx_full[which(dx_full$dx=="DYS"),]
dx_depressive_DNOS <-  dx_full[which(dx_full$dx=="DNOS"),]

dx_depressive <- full_join(dx_depressive_MDD, dx_depressive_DNOS)
dx_depressive <- full_join(dx_depressive, dx_depressive_DYS)

dx_depressive$dx[dx_depressive$dx=="MDD"] = "1"
dx_depressive$dx[dx_depressive$dx=="DYS"] = "2"
dx_depressive$dx[dx_depressive$dx=="DNOS"] = "3"


dx_depressive$Wave_1_C <- paste(dx_depressive$W1_current)
dx_depressive$Wave_1_P <- paste(dx_depressive$W1_past)
dx_depressive$Wave_2_C <- paste(dx_depressive$W2_current)
dx_depressive$Wave_2_P <- paste(dx_depressive$W2_past)
dx_depressive$Wave_3_C <- paste(dx_depressive$W3_current)
dx_depressive$Wave_3_P <- paste(dx_depressive$W3_past)

dx_depressive$Wave_1_C[dx_depressive$Wave_1_C=="1"] = "1"
dx_depressive$Wave_1_P[dx_depressive$Wave_1_P=="1"] = "1"
dx_depressive$Wave_2_C[dx_depressive$Wave_2_C=="1"] = "2"
dx_depressive$Wave_2_P[dx_depressive$Wave_2_P=="1"] = "2"
dx_depressive$Wave_3_C[dx_depressive$Wave_3_C=="1"] = "3"
dx_depressive$Wave_3_P[dx_depressive$Wave_3_P=="1"] = "3"

dx_depressive <- dx_depressive %>%
  unite("Wave", Wave_1_C:Wave_1_P:Wave_2_C:Wave_2_P:Wave_3_C:Wave_3_P)

dx_depressive <- dx_depressive %>%
  mutate(Wave=ifelse(Wave=="1_NA_NA_NA_NA_NA", "1",
                     ifelse(Wave=="NA_1_NA_NA_NA_NA", "1",
                            ifelse(Wave=="NA_NA_2_NA_NA_NA", "2",
                                   ifelse(Wave=="NA_NA_NA_2_NA_NA", "2",
                                          ifelse(Wave=="NA_NA_NA_NA_3_NA", "3",
                                                 ifelse(Wave=="NA_NA_NA_NA_NA_3", "3",
                                                        Wave)))))))

dx_depressive$Wave <- as.factor(dx_depressive$Wave)
dx_depressive$dx <- as.integer(dx_depressive$dx)

dx_depressive$onset_age_months_decimal <- dx_depressive$onset_age_months/12

dx_depressive$onset_age <- dx_depressive$onset_age_years + dx_depressive$onset_age_months_decimal

dx_depressive <-  dx_depressive[(-1),]

dep_dx_by_px<- ggplot(dx_depressive,
                           aes(x=dx,
                               y=onset_age,
                               group=ID,
                               col=Wave,
                               shape=Wave)) + 
  geom_point(alpha=1) + 
  geom_line(alpha=.4)+
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("W1", "W2", "W3"),
                     values = c("#5445b1", "#749dae", "#f3c483"))  +
  scale_shape_manual(name= "Wave",
              labels= c("W1", "W2", "W3"),
              values = c(0, 1, 2))+
  ylab("Age of Onset (years)") +
	ylim(5, 16) +
  xlab("Diagnosis Type")+
  scale_x_continuous(breaks = 1:3,
  labels = paste0(c("MDD", "DYS", "DNOS")))+
  theme_minimal()


```

